MODEL_ID = "LiquidAI/LFM2.5-1.2B-Instruct"
OUTPUT_MODEL_ID = "abdeljalilELmajjodi/darija_translator_54k"
DATASET_REPO = "abdeljalilELmajjodi/darija_english_54k_clean"
DATASET_CONFIG = "train"
OUTPUT_DIR = "LFM_2.5_Translator"
NUM_TRAIN_EPOCHS = 1
PER_DEVICE_TRAIN_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_BATCH_SIZE = 16
LEARNING_RATE = 2e-5
LR_SCHEDULER_TYPE = "cosine"
WARMUP_RATIO = 0.05
OPTIM = "paged_adamw_8bit"
BF16 = True
LOGGING_STEPS = 10
SAVE_STRATEGY = "steps"
SAVE_STEPS = 1000
SAVE_TOTAL_LIMIT = 2

PUSH_TO_HUB = False
# hub_model_id=OUTPUT_MODEL_ID,
# hub_strategy="every_save",
DATASET_TEXT_FIELD = "messages"
PACKING = False
REPORT_TO = "trackio"
